In [32]:
import urllib
import lxml
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import html5lib
import requests
url_ = "http://www.atlasf1.com/2003/aus/laptimes.html"

page = requests.get(url_)
soup = BeautifulSoup(page.content, 'html5lib')

In [56]:
import datetime
table = soup.find("table", class_="copyright")
df = pd.read_html(str(table), flavor='bs4', header=[0])[0]
#df.drop(["Unnamed: 0","Unnamed: 6"],axis=1, inplace=True)
dateparse = lambda x: pd.datetime.strptime(x, '%M:%S.%f')
seconds = lambda x: x.total_seconds()
df["Lap 1"] = df["Lap 1"].apply(dateparse)
df["Lap 1"] = df["Lap 1"] - datetime.datetime(1900,1,1)
df["Lap 1"] = df["Lap 1"].apply(seconds)
df.head()

C:\Users\marco\AppData\Local\Temp\ipykernel_4420\3537536607.py:5: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  dateparse = lambda x: pd.datetime.strptime(x, '%M:%S.%f')

,Driver,Lap 1,Lap 2,Lap 3,Lap 4,Lap 5,Lap 6,Lap 7,Lap 8,Lap 9,...,Lap 50,Unnamed: 55,Lap 51,Lap 52,Lap 53,Lap 54,Lap 55,Lap 56,Lap 57,Lap 58
0,"Schumacher, M",103.478,1:37.629,1:36.956,1:37.190,1:36.426,1:36.441,2:06.692,1:41.899,2:12.018,...,1:28.989,MSC,1:28.553,1:28.608,1:29.596,1:29.813,1:29.242,1:29.034,1:29.087,1:28.826
1,Barrichello,105.068,1:37.252,1:37.248,1:37.168,1:37.086,999:999,999:999,999:999,999:999,...,999:999,999:999,999:999,999:999,999:999,999:999,999:999,999:999,999:999,999:999
2,Montoya,111.388,1:40.983,1:37.725,1:34.663,1:33.619,1:33.562,1:32.319,1:31.107,2:46.999,...,1:29.449,MOY,1:29.202,1:29.319,1:29.692,1:29.947,1:29.224,1:28.954,1:28.802,1:29.345
3,"Schumacher, R",118.559,1:43.781,1:39.109,1:37.795,1:37.054,1:35.156,1:33.238,1:32.474,2:28.387,...,1:30.339,RSC,1:29.817,1:30.011,1:29.707,1:29.636,1:29.814,1:29.681,1:29.426,1:30.011
4,Coulthard,116.961,2:06.390,1:42.318,1:36.308,1:33.070,1:32.569,1:33.637,1:37.437,2:11.164,...,1:29.124,COU,1:29.298,1:29.246,1:29.006,1:29.063,1:29.426,1:29.923,1:30.289,1:31.285